# Simple pre-commit for personal projects - runs on push
repos:
  - repo: local
    hooks:
      - id: checkstyle
        name: 🎨 Checkstyle
        entry: ./mvnw checkstyle:check
        language: system
        files: \.java$
        pass_filenames: false
        stages: [push]