apiVersion: v1
kind: Secret
metadata:
  name: wallet-secrets
  namespace: wallet-service
type: Opaque
data:
  # MySQL passwords (base64 encoded)
  MYSQL_ROOT_PASSWORD: cm9vdA==  # root
  MYSQL_PASSWORD: d2FsbGV0  # wallet
  MYSQL_REPLICATION_PASSWORD: cmVwbA==  # repl
stringData:
  # MySQL users (plain text for readability)
  MYSQL_REPLICATION_USER: "repl"
  MYSQL_USER: "wallet"
